### PR TITLE
Prices added to "Buy" and "Rent" menu

### PR DESCRIPTION
**Pull request by JiminyKroket**
Good for pulling?

### CODE REVIEW

**Comment by WajihHalawani** [comment]
i'm kinda surprised that this feature is not already included.

**Comment by DennisFusha** [comment]
This doesn't work for me.

**Comment by userMacieG** [comment]
Better impl. of that:
`table.insert(elements, {label = _U('buy', ESX.Math.GroupDigits(property["price"])), value = 'buy'})
table.insert(elements, {label = _U('rent', ESX.Math.GroupDigits(property["price"] * 0.005)), value = 'rent'})`

and in langs for label "buy" and "rent" add  ' - $%s'

**Comment by DennisFusha** [comment]
> Better impl. of that:
> `table.insert(elements, {label = _U('buy', ESX.Math.GroupDigits(property["price"])), value = 'buy'}) table.insert(elements, {label = _U('rent', ESX.Math.Round(property["price"] / 200)), value = 'rent'})`
> 
> and changes in 375, 376 lines:
> `{label = _U('buy', ESX.Math.GroupDigits(property.price)), value = 'buy'}, {label = _U('rent', ESX.Math.Round(property["price"] / 200)), value = 'rent'},`
> 
> and in langs for label "buy" and "rent" add ' - $%s'

Can u contact me on discord and show me? doesn't work. Mr.BelgiumGamer#1378

**Comment by JiminyKroket** [comment]
Im in UHU are you?

**Pull request closed without merging**
